// All clubs that have played in the EDFL from 1930 to 2005
export const EDFL_CLUBS = [
  // Current clubs (noted in bold in original)
  { name: "Aberfeldie", current: true },
  { name: "Airport West", current: true },
  { name: "Avondale Heights", current: true },
  { name: "Deer Park", current: true },
  { name: "East Keilor", current: true },
  { name: "Essendon Doutta Stars", current: true },
  { name: "Glenroy", current: true },
  { name: "Greenvale", current: true },
  { name: "Keilor", current: true },
  { name: "Maribyrnong Park", current: true },
  { name: "Northern Saints", current: true },
  { name: "Pascoe Vale", current: true },
  { name: "Strathmore", current: true },
  { name: "West Coburg", current: true },

  // Historical clubs
  { name: "6th Melb. Scouts", current: false },
  { name: "Aberfeldie Park", current: false },
  { name: "All Nations Youth Club", current: false },
  { name: "Ascot Imperials", current: false },
  { name: "Ascot Presbyterians", current: false },
  { name: "Ascot Rovers", current: false },
  { name: "Ascot Rovers/Maribyrnong", current: false },
  { name: "Ascot United", current: false },
  { name: "Ascot Vale", current: false },
  { name: "Ascot Vale Methodists", current: false },
  { name: "Ascot Vale Wanderers", current: false },
  { name: "Ascot Vale West", current: false },
  { name: "Ascot Youth Centre", current: false },
  { name: "Australian National Airways", current: false },
  { name: "Batman", current: false },
  { name: "Broadmeadows", current: false },
  { name: "Brunswick City", current: false },
  { name: "Brunswick Colts", current: false },
  { name: "Brunswick Presbyterians", current: false },
  { name: "Brunswick Sons of Soldiers", current: false },
  { name: "Brunswick United", current: false },
  { name: "Catholic Boys Club", current: false },
  { name: "Coburg Amateurs", current: false },
  { name: "Coburg Districts", current: false },
  { name: "Coburg Rovers", current: false },
  { name: "Coburg Sons of Soldiers", current: false },
  { name: "Coburg Stars", current: false },
  { name: "Coburgians", current: false },
  { name: "Corpus Christi", current: false },
  { name: "Craigieburn", current: false },
  { name: "Don Rovers", current: false },
  { name: "Doutta Stars", current: false },
  { name: "East Brunswick", current: false },
  { name: "East Coburg", current: false },
  { name: "East Essendon", current: false },
  { name: "Essendon All Blacks", current: false },
  { name: "Essendon Baptist", current: false },
  { name: "Essendon Baptist St.Johns", current: false },
  { name: "Essendon Bombers", current: false },
  { name: "Essendon Church of Christ", current: false },
  { name: "Essendon Grammar Old Boys", current: false },
  { name: "Essendon High School Old Boys", current: false },
  { name: "Essendon Imperials", current: false },
  { name: "Essendon Returned Soldiers", current: false },
  { name: "Essendon Sons of Soldiers", current: false },
  { name: "Essendon Stars", current: false },
  { name: "Essendon Swimmers Old", current: false },
  { name: "Essendon Tullamarine", current: false },
  { name: "Essendon United", current: false },
  { name: "Essendon Youth Centre", current: false },
  { name: "Fairbairn Rovers", current: false },
  { name: "Fairbairn Socials", current: false },
  { name: "Fawkner Districts", current: false },
  { name: "Flemington/Kensington", current: false },
  { name: "Footscray Technical College", current: false },
  { name: "Ford Company", current: false },
  { name: "Gladstone Park", current: false },
  { name: "Glenbervie", current: false },
  { name: "Hadfield", current: false },
  { name: "Jacana", current: false },
  { name: "Keilor Park", current: false },
  { name: "Keilor Regal Sports", current: false },
  { name: "Kensington Methodists", current: false },
  { name: "Knox Presbyterians", current: false },
  { name: "La Mascotte", current: false },
  { name: "Lincoln Rovers", current: false },
  { name: "Lincoln Stars", current: false },
  { name: "Lincoln Tigers", current: false },
  { name: "Maribyrnong", current: false },
  { name: "Maribyrnong-Ascot United", current: false },
  { name: "Maribyrnong Regal Sport", current: false },
  { name: "Maribyrnong Youth Club", current: false },
  { name: "Marrows", current: false },
  { name: "Meadows Heights", current: false },
  { name: "Monash Rovers", current: false },
  { name: "Moonee Imps", current: false },
  { name: "Moonee Ponds", current: false },
  { name: "Moonee Ponds YCW", current: false },
  { name: "Moonee Valley", current: false },
  { name: "Moonee Valley Juniors", current: false },
  { name: "North Coburg Saints", current: false },
  { name: "North Essendon Methodists", current: false },
  { name: "Northcote Excelsior", current: false },
  { name: "Northern Juniors", current: false },
  { name: "Northern Rovers", current: false },
  { name: "Oak Park", current: false },
  { name: "Parkville", current: false },
  { name: "Raeburn", current: false },
  { name: "Regal Sports", current: false },
  { name: "Riverside Stars", current: false },
  { name: "Roxburgh Park", current: false },
  { name: "Royal Park", current: false },
  { name: "South Kensington", current: false },
  { name: "St. Andrews", current: false },
  { name: "St. Bernards", current: false },
  { name: "St. Bernards Juniors", current: false },
  { name: "St. Christophers", current: false },
  { name: "St. Davids", current: false },
  { name: "St. Francis", current: false },
  { name: "St. Johns", current: false },
  { name: "St. Monicas CYMS", current: false },
  { name: "St. Olivers", current: false },
  { name: "St. Patricks", current: false },
  { name: "St. Pauls", current: false },
  { name: "Strathmore Stars", current: false },
  { name: "Sydenham Hillside", current: false },
  { name: "Taylors Lakes", current: false },
  { name: "Tullamarine", current: false },
  { name: "Tullamarine/Airport West", current: false },
  { name: "Tullamarine Ascot Presbyterians", current: false },
  { name: "Vespa", current: false },
  { name: "West Brunswick", current: false },
  { name: "West Brunswick Laurels", current: false },
  { name: "West Coburg Amateurs", current: false },
  { name: "West Coburg Juniors", current: false },
  { name: "West Coburg Seniors", current: false },
  { name: "West Essendon", current: false },
  { name: "West Essendon Youth Center", current: false },
  { name: "West Moreland", current: false },
  { name: "Westmeadows", current: false },
  { name: "Woodlands", current: false },
]

export const getCurrentClubs = () => EDFL_CLUBS.filter((club) => club.current)
export const getHistoricalClubs = () => EDFL_CLUBS.filter((club) => !club.current)
export const getAllClubs = () => EDFL_CLUBS

// Helper function to create URL-safe slugs
export const createClubSlug = (clubName: string): string => {
  return clubName
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "") // Remove special characters except spaces and hyphens
    .replace(/\s+/g, "-") // Replace spaces with hyphens
    .replace(/-+/g, "-") // Replace multiple hyphens with single hyphen
    .trim()
}

// Helper function to get club by slug
export const getClubBySlug = (slug: string) => {
  return EDFL_CLUBS.find((club) => createClubSlug(club.name) === slug)
}

// Export the main array with the expected name
export const edflClubs = EDFL_CLUBS
